### ISSUE TITLE
Some link changes :)

### ISSUE THREAD

**Issue by wu-hongjun** [tylernguyen/razer15-hackintosh#2]
Hey!

Happy to see you are using my readme as a template :) Just FYI you might want to change some of the links in the readme too if you are changing the license.

Happy hackintoshing lol

**Comment by tylernguyen** [comment]
@Errrneist Hey there, thanks for stopping by. And yeah, this repo is due for an update soon for broken links and more documentations.

**Comment by wu-hongjun** [comment]
I was just looking around for solutions for thunderbolt 3. Do you happen to have thunderbolt working for your machine? Also, what did you do to set Macintosh as the default boot option? (Aka skip the selection screen) thanks.

Another note: you can actually use hackintool to patch your iGPU which will not only give you 2048MB of VRAM but also fix the screen glitching issues, if any.

**Comment by tylernguyen** [comment]
@Errrneist I haven't had to time to fix Thunderbolt hotplug yet. However, it will likely be some sort of solution with [ThunderReset.kext](https://github.com/osy86/ThunderboltReset) and [TbtForcePower.efi](https://github.com/al3xtjames/ThunderboltPkg) and a custom patch to point it to the right hotplug path.

Regarding boot options, the easy fix is enabling `Bootstap.efi` support. Make you sure the .efi driver in the Bootstrap folder and set `BootProtect` to `Bootstrap` within OpenCore `config.plist`. A BIOS option called `OpenCore` should be created and you can set that as default within BIOS.

**Comment by wu-hongjun** [comment]
Awesome. I’ll look into it.

**Comment by tylernguyen** [comment]
@Errrneist Btw, `framebuffer-unifiedmem` is not recommended per WhateverGreen's [doc](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md).

Framebuffer patching is complicated and can be time consuming. But I would recommend you do it manually, Hackintool should really only be used for diagnosing.

And I'm not sure which CPU you have but mine has native graphics support after BIOS modding. So nothing is really need on that side.
